version: '1'
services:
  swt:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - mysql
    - ssh-agent
  mysql:
    image: mysql
  ssh-agent:
    image: ssh-agent
volumes:
  logvolume01: {}